language: node_js
node_js:
  - 0.12
branches:
  only:
      - master
notifications:
  email: false
  irc: "160.16.84.17#travis"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
